### ISSUE TITLE
Diagram Subsystems with device ids

### ISSUE THREAD

**Issue by peterpde** [619Code/Robot2022#25]
Diagraming all subsystems and their associated device ids.  See #17

**Comment by rivques** [comment]
Drew diagram, still need to fill out IDs. Need to communicate with Daniel and electronics

**Comment by rivques** [comment]
Completed ![Completed diagram](https://cdn.discordapp.com/attachments/681549506319614139/948016398100230234/E5B802EC-7636-4AD5-8EEE-772813B6854C.jpg)
